version: "3.9"
services:
  db:
    build: ./db
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_DATABASE: ${MYSQL_DATABASE:-mydb}
      MYSQL_TESTDATABASE: ${MYSQL_TESTDATABASE:-testdb}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_USER: ${MYSQL_USER:-dbuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
    volumes:
      - order-db-volume:/var/lib/mysql
      - ./db/cnf:/etc/mysql/conf.d
    ports:
      - "${MYSQL_PORT:-3306}:3306"
  api:
    build: ./api
    volumes:
      - ./api:/var/www/
    ports:
      - "8080:8080"
volumes:
  order-db-volume:
    external: true
